console.log(1==1);
console.log(1=="1");
console.log(1==1.0);
Console.log("" ==0);
Console.log(0==[]);
Console.log("" ==[]);
Console.log(" "==0);
Console.log(""==[]);
Console.log(" "==0);
Console.log(" "=="");
Console.log(" "=="");
